---
title: "Sheep Androgen Clock Construction - BBA-seq approach, 5% error"
author: "Victoria Sugrue"
date: 'Last updated: 15 May 2023'
output:
  word_document:
    toc: yes
    toc_depth: '6'
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
  pdf_document:
    toc: yes
    toc_depth: 5
    df_print: kable
    latex_engine: xelatex
subtitle: ' '
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load required packages
```{r}
library(ggplot2)
library(caret)
library(dplyr)
library(Manu)
library(knitr)
library(sjPlot)
library(lmtest)
library(Amelia)
library(mlbench)
library(ggfortify)
```

### Data preparation
```{r}
sheep_data <- read.csv("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Bioinformatics/Data/SheepSampleSheet.csv")

# Setting AndroAge with predicted time of puberty onset = age minus 0.5 years (i.e estimate to reach puberty at 6 months)
sheep_data$YPMP <- sheep_data$Age-0.5
sheep_data$YPMP[sheep_data$Castration_Sex=="Wether"] <- 0
sheep_data$YPMP[sheep_data$Castration_Sex=="Ewe"] <- 0

# Creating a new column for methylation in the form of a beta value
sheep_data$Beta <- sheep_data$CG_Methylation/100

# Subset by sex/castration status
ram_data <- sheep_data %>% filter(Castration_Sex=="Ram")
wether_data <- sheep_data %>% filter(Castration_Sex=="Wether")
ewe_data <- sheep_data %>% filter(Castration_Sex=="Ewe")

```

### A birds-eye view of the data 

```{r}
# Subset based on error allowance
sheep_data_5 <- sheep_data %>% filter(CG_Calls>=497)

# Age distribution with +/- 5% error in 75% methylated samples
age_dist_5 <- ggplot(sheep_data_5, aes(x = Age)) +
  geom_histogram(aes(fill = Castration_Sex), position = "dodge", alpha = 1, bins = 20) +
  scale_fill_manual(values = get_pal("Takahe")[c(1,2,4)]) +
  theme_light() +
  labs(title = "Distribution of age by sex (Sheep ear), >497 CG calls (±5% error at 75% methyated)", fill = "Sex", x="Age (Years)") +
  ylab("Frequency")
age_dist_5

ggsave("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Figures/age_distribution_clockSheep_5.png",age_dist_5, width=10, height = 8, dpi=1000)
```

### Plotting methylation data

```{r}
# +/- 5% error in 75% methylated samples
MKLN1_sheep_5 <- ggplot(sheep_data_5, aes(x=Age, y=CG_Methylation, colour=Castration_Sex)) +
  geom_jitter(width=0.1, size=4, alpha=2/3) +
  geom_smooth(method="lm") +
  scale_colour_manual(values = get_pal("Takahe")[c(1,2,4)]) +
  theme_light() +
  labs(title = "Methylation at cg21524116, >497 CG calls (±5% error at 75% methyated)", colour="Sex", y="Methylation (%)", x="Age (Years)")
MKLN1_sheep_5

ggsave("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Figures/MKLN1_meth_sheepear_5.png",MKLN1_sheep_5, width=10, height = 8, dpi=1000)
```

# Fitting the Androgen Clock to rams

```{r}
ram_data_5 <- ram_data %>% filter(CG_Calls>=497)
```


```{r}
# Run model, 5% error
model_5p <- lm(YPMP ~ Beta, data=ram_data_5)
summary(model_5p)
```

### Diagnostic plots

```{r}
autoplot(model_5p, which=c(1,2,3,5), size=3, alpha=4/5, colour="#313657", smooth.colour="#DD3C51", smooth.linetype="dashed", label.size = 3) + theme_light() + theme(plot.title = element_text(color = "white"))
```


```{r}
fitted_5 <- as.data.frame(model_5p$fitted.values)
fitted_5["YPMP"] <- ram_data_5$YPMP
fitted_5$YPMP <- as.numeric(fitted_5$YPMP)
fitted_5$Fit_AndroAge <- as.numeric(fitted_5$`model_5p$fitted.values`)
fitted_5$Age <- ram_data_5$Age
```

# Calculating error
### All

```{r}
MAE_model_5p <- as.data.frame(Metrics::mae(actual=fitted_5$YPMP, predicted=fitted_5$`model_5p$fitted.values`))
MAE_model_5p # 0.569
```

### Plot 

```{r}
cor(fitted_5$YPMP, fitted_5$Fit_AndroAge, method="pearson")

ramfit5 <- ggplot(fitted_5, aes(x=YPMP, y=Fit_AndroAge)) +
  geom_point(size=4, alpha=3/4, colour="#313657") + 
  geom_smooth(method="lm", se=F, colour="#DD3C51") +
  geom_abline(linetype="dashed") +
  theme_light() +
  ylab("Model AndroAge (Years)") +
  xlab("Years Post Male Puberty (YPMP)") +
  labs(title = "Ram androgen clock fit (model_5p), trained on all",
              subtitle = "MAE=0.569, cor=0.912") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5))

ramfit5
ggsave("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Figures/5errormodel_ramFit.png",ramfit5, width=8, height = 7, dpi=1000)

```


### Testing the model fit further: 

#### Breusch-Pagan test of variance (homo/heteroscedasticity)

```{r}
bptest(model_5p)
#0.06
# p value >0.05 suggests that we have homoscedasticity. good! 

```

#### Shapiro-Wilk test of normality

```{r}
shapiro.test(model_5p$residuals)
# 0.90
# p value >0.05 suggests data is normally distributed. good!
```


# Leave-one-out cross validation

```{r}
ram_data_5$Beta <- as.numeric(ram_data_5$Beta)
ram_data_5$YPMP <- as.numeric(ram_data_5$YPMP)
ctrl <- trainControl(method="LOOCV")
model_5p_LOO <- train(YPMP ~ Beta, data=ram_data_5, method="lm", trControl=ctrl)
summary(model_5p_LOO)
```

```{r}
print(model_5p_LOO)
```

```{r}
fittedLOO_5 <- as.data.frame(model_5p_LOO$pred)
fittedLOO_5["YPMP"] <- ram_data_5$YPMP

LOORamAndroClockMAE_5 <- as.data.frame(Metrics::mae(actual=fittedLOO_5$YPMP, predicted=fittedLOO_5$pred))
LOORamAndroClockMAE_5 # 0.579
```

```{r}
cor(fittedLOO_5$obs, fittedLOO_5$pred, method="pearson")

ramLOOfit5 <- ggplot(fittedLOO_5, aes(x=obs, y=pred)) +
  geom_point(size=4, alpha=3/4, colour="#313657") + 
  geom_smooth(method="lm", se=F, colour="#DD3C51") +
  geom_abline(linetype="dashed") +
  theme_light() +
  ylab("Model AndroAge (Years)") +
  xlab("Years Post Male Puberty (YPMP)") +
  labs(title = "Ram androgen clock fit (model_5p), LOOCV",
              subtitle = "MAE=0.579, cor=0.909") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5))
ramLOOfit5
ggsave("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Figures/5errormodel_LOO_ramFit.png",ramLOOfit5, width=8, height = 7, dpi=1000)

```

# Now, to include ewes and wethers.

```{r}
ewe_data_5 <- ewe_data %>% filter(CG_Calls>=497)
ewe_data_5$Model_AndroAge <- predict(model_5p, newdata = ewe_data_5)

ewe_MAE_model_5p <- as.data.frame(Metrics::mae(actual=ewe_data_5$YPMP, predicted=ewe_data_5$Model_AndroAge))
ewe_MAE_model_5p
# Ewe MAE = 0.38 years
```


```{r}
wether_data_5 <- wether_data %>% filter(CG_Calls>=497)
wether_data_5$Model_AndroAge <- predict(model_5p, newdata = wether_data_5)

wether_MAE_model_5p <- as.data.frame(Metrics::mae(actual=wether_data_5$YPMP, predicted=wether_data_5$Model_AndroAge))
wether_MAE_model_5p
# Wether MAE = 0.33 years

ewewether_5 <- rbind(ewe_data_5, wether_data_5)

ewewether_5_violin <- ggplot(ewewether_5, aes(x=Castration_Sex, y=Model_AndroAge, fill=Castration_Sex)) +
  geom_violin() + 
  geom_point(size=4, alpha=3/4, shape=1) +
  theme_light() +
  geom_hline(yintercept = 0, linetype="dashed") +
  ylab("Model AndroAge (Years)") +
  xlab("Sex") +
  scale_fill_manual(values = get_pal("Takahe")[c(1,4)]) +
  theme(legend.position = "none") +
   labs(title = "Ewe and wether androgen clock fit (model_5p), trained on all rams",
              subtitle = "Ewe MAE=0.389, Wether MAE=0.331") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5))
  
ewewether_5_violin

ggsave("/Users/victoriasugrue/Dropbox (Otago University)/00_ThesisWriting/Figures/5errormodel_ewewetherFit_violin.png",ewewether_5_violin, width=11, height = 6, dpi=1000)

```